
image: node:latest

stages:
  - check


typescript_check:
  stage: check
  script:
    - npm ci
    - DATABASE_URL="postgresql://dummy:dummy@dummy/dummy" npx prisma generate
    - npx tsc --noEmit
    
